Revert "Revert "Chacha20""
pluto/web-prover-circuits pull request #51
Opened 2024-11-19 16:05 UTC by 0xJepsen

Reverts pluto/web-prover-circuits#50

This one is reopen so now you can review

2024-11-19 20:28 UTC, Autoparallel commented
lol the name here

2024-11-19 21:05 UTC, Autoparallel requested changes
Some changes requested here. Mostly to not remove AES.

2024-11-19 21:05 UTC, Autoparallel commented on circuits/test/full/full.test.ts
> -    let aesCircuit: WitnessTester<["key", "iv", "aad", "ctr", "plainText", "cipherText", "step_in"], ["step_out"]>;
I'm not a fan of deleting a whole test case. We may want to come back to AES. We don't know yet, but I don't want to remove this circuit and its test in this PR.

In general, PRs should do one thing -- this one adds fodlable ChaCha20. It should not remove AES-GCTR. This is the main reason this got reverted.

2024-11-19 21:05 UTC, Autoparallel commented on circuits/utils/generics-bits.circom
> +        out[i] <== in[(i + L) % BITS];
modular arithmetic is the best thing

2024-11-19 21:05 UTC, Autoparallel commented on package.json
> +  "version": "0.6.0",
I'm partial to putting this as `v0.5.5` as this does not break an API here. It introduces an extended API.

This is less important to me though. I could go either way.

2024-11-20 03:59 UTC, 0xJepsen commented on circuits/chacha20/nivc/chacha20_nivc.circom
> +	// the below can be both ciphertext or plaintext depending on the direction
yes thats exactly correct. this circuit is entirely symmetric.

2024-11-20 04:01 UTC, 0xJepsen commented on circuits/test/full/full.test.ts
> -    let aesCircuit: WitnessTester<["key", "iv", "aad", "ctr", "plainText", "cipherText", "step_in"], ["step_out"]>;
So what should we use in the full test AES or ChaCha?

2024-11-20 04:06 UTC, 0xJepsen commented on circuits/chacha20/chacha-qr.circom
> +	component add1 = AddBits(32);
Good question. I don't know, perhaps it's worth looking into if this circuits performance becomes a problem.

2024-11-20 04:16 UTC, 0xJepsen commented on circuits/test/full/full.test.ts
> -    let aesCircuit: WitnessTester<["key", "iv", "aad", "ctr", "plainText", "cipherText", "step_in"], ["step_out"]>;
I actually just put them both back in the full test for now which seems best.

2024-11-20 13:21 UTC, Autoparallel commented on circuits/test/full/full.test.ts
> -    let aesCircuit: WitnessTester<["key", "iv", "aad", "ctr", "plainText", "cipherText", "step_in"], ["step_out"]>;
Yes, both. Just have `NIVC_FULL_AES` and `NIVC_FULL_CHACHA`

2024-11-21 19:53 UTC, Autoparallel commented on circuits/chacha20/nivc/chacha20_nivc.circom
> +	signal input plainText[N][32];
I think it would be preferable to have this take in bytes instead of bits. But maybe its not a big deal at all.

2024-11-21 22:18 UTC, Autoparallel approved these changes
Okay, in my opinion this can be merged so we can move along, but I honestly feel like this could be made quite a bit cleaner and clearer. 

For one, I think it would probably serve us to have `ChaCha20` take in bytes, not bits. Would be as easy as calling `ByteToBits` or `ToBits(8)` or whatever the template is. This makes life easier on the Rust side. It's not a big deal either way I suppose, but this just changes the API in an unexpected way, in my opinion.

Second, the way the full tests were laid out is, bizarre. If I was being stricter here, I'd ask you to redo it in the following way:
1. Leave the `NIVC_FULL` and `NIVC_FULL_2` tests as is, but rename them to `NIVC_FULL_AES` and `NIVC_FULL_2_AES`.
2. Create two tests `NIVC_FULL_CHACHA` and `NIVC_FULL_2_CHACHA`. 
3. I think we should be testing these circuits in the same way we tested AES-GCTR here. The first `NIVC_FULL` folds a single 16 byte chunk at a time, `NIVC_FULL` folds 32 bytes at a time. You could mimic this with ChaCha by having `NIVC_FULL_CHACHA` run with all 320 bytes at once. Then `NIVC_FULL_CHACHA_2` could do 160 bytes at once. This tests that the parameter for how many 32bit words to fold at once works with our circuit chain. It almost certainly does, but why not just test it that way?

Please consider taking this feedback and integrating it before you merge this. If not, then make issues at least, please!

2024-11-21 22:18 UTC, Autoparallel commented on circuits/test/full/full.test.ts
>      it("NIVC_CHAIN", async () => {
Okay, the way you did this test is a bit... odd.

Why not just make a two tests for each? We already had two AES full tests, and you could've just mimicked them for ChaCha20 in some reasonable sense. It's honestly a bit hard to get what these tests do without spending 10 minutes reading through them line by line

2024-11-22 03:31 UTC, 0xJepsen commented on circuits/chacha20/nivc/chacha20_nivc.circom
> +	signal input plainText[N][32];
yes i understand. Doing so would increase the constraints in the circuit though.

2024-11-22 03:35 UTC, 0xJepsen commented on circuits/test/full/full.test.ts
>      it("NIVC_CHAIN", async () => {
The reason i did it this was was to show that the output from chacha and aes is the same for some plaintext.

2024-11-22 03:40 UTC, 0xJepsen commented on circuits/test/full/full.test.ts
>      it("NIVC_CHAIN", async () => {
I will do it the way you suggested.

2024-11-22 04:47 UTC, merged