release: v0.6.0
pluto/web-prover-circuits pull request #65
Opened 2024-12-03 20:00 UTC by Autoparallel

WIP: Staging

2024-12-03 22:56 UTC, Autoparallel commented
I'm going to squash these commits down once I see that we are passing CI again. I fat fingered my changes to `main.rs` so I broke the artifact workflow.

2024-12-03 23:14 UTC, Autoparallel commented
Branch is clean now, force push done!

2024-12-05 17:56 UTC, 0xJepsen commented on circuits/chacha20/nivc/chacha20_nivc.circom
> +      bigEndianCiphertext[i*4 + j] <== isPadding[i * 4 + j] * (-1 - toCiphertextBytes[i].words[j]) + toCiphertextBytes[i].words[j]; // equal to: (isPadding[i * 4 + j] * (-1)) + (1 - isPadding[i * 4 +
nice

2024-12-05 20:09 UTC, 0xJepsen commented on Makefile
> +		circom "$${circuit}" --r1cs --wasm --O1 -o "$$(dirname $${circuit})/artifacts" -l node_modules; \
opt --02 is broken?

2024-12-05 20:22 UTC, lonerapier requested changes
sleep score after this PR lands: 10 -> 90

Seriously, so much of this is just dead weight. Thanks for spending time to clean this up thoroughly. this will also reduce amount of TODOs significantly.

I have really really minor nits along with following questions:
1. Can we remove dead docs from `docs/` and README?
  a. Can we also add new really small doc for NIVC circuits? Can be totally done in a separate PR. Actually, i'll myself really love to do that.
2. Circuit sizes is really huge right now, and it's for all circuits. My suspicion is on `DataHasher`, because that is only new common thing added to all circuits. Anyways, we should definitely check and bench the constraint size and r1cs size of circuit. (I am happy to do that)
3. Can we remove unused example files in `examples/` directory?

2024-12-05 20:22 UTC, lonerapier commented on circuits/http/verification.circom
> +        start_line[i]          <== data[i] * (1 - not_start_line_mask[i]);
please tell me you do not do this manually, because I've seen you do this multiple times, and i feel guilty of not doing this in previous PRs lol

2024-12-06 12:31 UTC, lonerapier commented on circuits/json/nivc/masker.circom
>      assert(MAX_STACK_HEIGHT >= 2); // TODO (autoparallel): idk if we need this now
removed this

2024-12-06 12:32 UTC, lonerapier commented on circuits/json/parser/machine.circom
> +    readStartBrace.in        <== [byte, Syntax.START_BRACE];
checked it no warning. but there were others which have been removed in https://github.com/pluto/web-prover-circuits/pull/65/commits/f9ef0bc17377aff4fe49dcc3013d314017e0bc5c

2024-12-06 12:32 UTC, lonerapier commented on circuits/test/utils/search.test.ts
>  import witness from "../../../inputs/search/witness.json";
removed this and added hardcoded string

2024-12-06 12:33 UTC, lonerapier approved these changes
deleted old unused docs/example files and removed some circuit warnings.

**v0.6.0**, say it loudd

2024-12-06 12:33 UTC, merged